import { SPECTRAL_ENVELOPE } from '../fx/SpectralEnvelope.js';
import { AdditiveBlending, BufferGeometry, Float32BufferAttribute, Group, LineBasicMaterial, LineSegments, Mesh, MeshBasicMaterial, ConeGeometry, BoxGeometry, ShaderMaterial, SphereGeometry, Vector3 } from 'three';

export const SWORD_SKILLS={judgement:{cost:12,range:18,damage:24,radius:1.6},summon:{cost:8,range:20,damage:9},end:{range:9,damage:24}};
export function withinSwordRange(origin,point,range){return origin.distanceTo(point)<=range;}
export function segmentDistance(point,a,b){const d=b.clone().sub(a),u=Math.max(0,Math.min(1,point.clone().sub(a).dot(d)/(d.lengthSq()||1)));return point.distanceTo(a.clone().addScaledVector(d,u));}

/** Original reconstruction of the reference techniques; no imported game assets. */
export class VergilTechniques {
 constructor(p){this.p=p;this.g=p.game;this.projectiles=[];this.strokes=[];this.mode=0;this.cooldown=0;this.group=new Group();this.group.name='Katana spectral techniques';this.g.app.scene.add(this.group);
  this.geometry=new BufferGeometry();this.lines=new LineSegments(this.geometry,new ShaderMaterial({transparent:true,depthWrite:false,blending:AdditiveBlending,vertexShader:'attribute float aAge;varying float vAge;void main(){vAge=aAge;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:SPECTRAL_ENVELOPE+'varying float vAge;void main(){float alpha=getFloatOverLifetime(clamp(vAge,0.0,1.0),vec4(.15,.9,.35,0.));gl_FragColor=vec4(.65,.85,1.,alpha);}'}));this.lines.frustumCulled=false;this.group.add(this.lines);
  this.spheres=Array.from({length:8},()=>{const mesh=new Mesh(new SphereGeometry(1,12,8),new MeshBasicMaterial({color:'#99cbff',transparent:true,opacity:.12,wireframe:true,depthWrite:false}));mesh.visible=false;this.group.add(mesh);return {mesh,life:0};});
  this.guardGeometry=new BoxGeometry(.16,.025,.035);this.handleGeometry=new BoxGeometry(.025,.14,.025);
  this.bladeGeometry=new ConeGeometry(.035,.65,4);this.bladeMaterial=new MeshBasicMaterial({color:'#9ed9ff',transparent:true,opacity:.75,depthWrite:false});
 }
 reset(){this.ritual=null;this.mode=0;this.burstPending=false;for(const shot of this.projectiles)shot.mesh.removeFromParent();this.projectiles=[];this.strokes=[];for(const s of this.spheres){s.life=0;s.mesh.visible=false;}this.cooldown=0;this.p.arts?.cancel();}
 target(range=18){const p=this.p,t=p.lockTarget?.alive?p.lockTarget:p._autoTarget({reach:range,arc:120},range);return t&&withinSwordRange(p.character.position,t.position,range)&&this.g.targetVisible(t)!==false?t:null;}
 point(t){const c=this.p.character;return t?t.position.clone().add(new Vector3(0,1,0)):c.position.clone().add(new Vector3(Math.sin(c.facing)*6,1,Math.cos(c.facing)*6));}
 stroke(at,wide=false){const sphere=this.spheres.find(s=>s.life<=0)??this.spheres[0];sphere.life=.28;sphere.mesh.visible=true;sphere.mesh.position.copy(at);sphere.mesh.scale.setScalar(wide?1.5:.9);const count=this.g.quality.name==='low'?3:5;for(let i=0;i<count;i++){const d=new Vector3(Math.cos(i*2.4),Math.sin(i*2.4),Math.sin(i*1.7)).normalize().multiplyScalar(wide?2:1);this.strokes.push({a:at.clone().sub(d),b:at.clone().add(d),life:.28});}this.g.fx.glow.spawn(at,'#ddf4ff',wide?1.8:.65,.16,{star:true,grow:1,intensity:1.4});this.g.fx.flare(at,'#9bd6ff',wide?8:4,.12);}
 damage(at,radius,damage,source='spell',launch=false,only=null){let hits=0;for(const e of this.g.enemies.enemies){if(only&&e!==only)continue;if(!e.alive||!e.agent||this.g.targetVisible(e)===false||!withinSwordRange(this.p.character.position,e.position,source==='special'?9:20))continue;if(e.position.clone().add(new Vector3(0,1,0)).distanceTo(at)>radius+(e.agent.radius??.4))continue;const d=e.position.clone().sub(this.p.character.position).setY(0).normalize();const r=this.g.damageEnemy(e,{damage:damage*(this.p.arts.transform>0?1.25:1),posture:damage*.6,knockback:.3,launch,dirX:d.x,dirZ:d.z,source,heavy:source==='special',force:{impulse:2,lift:launch?3:.1,spin:0,slices:true}});if(r?.damage>0)hits++;}return hits;}
 summon(kind){const p=this.p,t=this.target(20),point=this.point(t),n=kind==='burst'?5:kind==='storm'?4:kind===2?6:kind===1?5:1;
  for(let i=0;i<n;i++){const angle=i*Math.PI*2/n,home=p.character.position.clone().add(new Vector3(Math.cos(angle)*.65,1.4,Math.sin(angle)*.65));const from=kind===2?point.clone().add(new Vector3(Math.cos(angle)*.65,3,Math.sin(angle)*.65)):kind==='storm'?point.clone().add(new Vector3(Math.cos(angle)*1.8,.1,Math.sin(angle)*1.8)):kind===0?this.point(null).copy(p.character.position).add(new Vector3(-Math.cos(p.character.facing)*.3,1.35,Math.sin(p.character.facing)*.3)):home;
   const mesh=new Group(),steel=new Mesh(this.bladeGeometry,this.bladeMaterial),guard=new Mesh(this.guardGeometry,this.bladeMaterial),handle=new Mesh(this.handleGeometry,this.bladeMaterial);steel.position.y=.10;guard.position.y=-.22;handle.position.y=-.29;mesh.add(steel,guard,handle);this.group.add(mesh);this.projectiles.push({mesh,pos:from.clone(),from,point:point.clone(),t:0,delay:kind===1?.65:kind==='burst'?.10*i:kind==='storm'?.3:kind===2?.08*i:0,orbit:kind===1,angle,hit:false});
  }
  this.g.audio.play('charge',{volume:.4,pitch:1.3});
 }
 startRitual(end){const p=this.p;for(const m of p.moves)m.cancel();p._cancelPoses();p._toFree();p.guarding=false;p.arts.charge();this.ritual={t:0,end,struck:0,point:this.point(this.target(end?9:18))};this.g.hud.notice(end?'次元斬・絶':'次元斬',1);this.g.audio.play('charge');}
 update(dt,input){const p=this.p,g=this.g,c=p.character;if(p.dead){this.reset();return undefined;}this.cooldown=Math.max(0,this.cooldown-dt);p.arts.transform=Math.max(0,p.arts.transform-dt);
  for(let i=this.projectiles.length-1;i>=0;i--){const s=this.projectiles[i];s.t+=dt;const previous=s.pos.clone();if(s.orbit&&s.t<s.delay){s.pos.copy(c.position).add(new Vector3(Math.cos(s.angle+s.t*7)*.7,1.25,Math.sin(s.angle+s.t*7)*.7));s.from.copy(s.pos);}else if(s.t>=s.delay){const d=s.point.clone().sub(s.pos),step=22*dt;if(d.length()<=step)s.pos.copy(s.point);else s.pos.addScaledVector(d.normalize(),step);for(const e of g.enemies.enemies){if(!e.alive||g.targetVisible(e)===false)continue;if(segmentDistance(e.position.clone().add(new Vector3(0,1,0)),previous,s.pos)<.3+(e.agent?.radius??.4)){this.stroke(s.pos);this.damage(s.pos,.45,9);s.hit=true;break;}}if(s.pos.distanceTo(s.point)<.05)s.hit=true;}s.mesh.position.copy(s.pos);const direction=s.point.clone().sub(s.pos).normalize();if(direction.lengthSq())s.mesh.quaternion.setFromUnitVectors(new Vector3(0,1,0),direction);if(s.hit||s.t>2){s.mesh.removeFromParent();this.projectiles.splice(i,1);}}
  this.strokes=this.strokes.filter(s=>(s.life-=dt)>0);const points=[],ages=[];for(const s of this.strokes){points.push(...s.a.toArray(),...s.b.toArray());ages.push(1-s.life/.28,1-s.life/.28);}this.geometry.setAttribute('position',new Float32BufferAttribute(points,3));this.geometry.setAttribute('aAge',new Float32BufferAttribute(ages,1));for(const s of this.spheres){s.life=Math.max(0,s.life-dt);s.mesh.visible=s.life>0;s.mesh.material.opacity=.12*s.life/.28;}this.geometry.computeBoundingSphere();
  if(p.dead||['hurt','down'].includes(p.state)||g.cinematic){if(this.ritual){this.ritual=null;p.arts.cancel();}return undefined;}
  if(this.ritual){const r=this.ritual;r.t+=dt;p.arts.t=r.t;if(input.pending('dodge')||input.pending('guard')){this.ritual=null;p.arts.cancel();return undefined;}const times=r.end?[.55,.75,.95]:[.38];if(r.struck<times.length&&r.t>=times[r.struck]){r.struck++;if(r.end){for(const e of g.enemies.enemies)if(e.alive&&g.targetVisible(e)!==false&&withinSwordRange(c.position,e.position,9)){const at=this.point(e);this.stroke(at,true);this.damage(at,.5,24,'special',false,e);}}else{this.stroke(r.point);this.damage(r.point,1.6,24);}g.audio.play('heavy',{volume:.55,pitch:1.25});}if(r.t>(r.end?1.35:.72)){this.ritual=null;p.arts.cancel();p.arts.startSheath();}return p._hold();}
  if(input.consume('special')){if(p.arts.transform>0){p.arts.transform=0;g.hud.notice('竜人化解除',1);}else if(p.special>=.5){p.special-=.5;p.arts.transform=8;g.hud.notice('竜人化 — 刀技強化',1.5);this.stroke(c.position.clone().add(new Vector3(0,1,0)),true);}else g.hud.notice('竜人化ゲージが足りない',1);return undefined;}
  if(input.pending('finish')&&p._canCancel(.6)&&!c.airHeight){input.consume('finish');if(p.special>=1){p.special=0;this.startRitual(true);return p._hold();}g.hud.notice('奥義ゲージが足りない',1);}
  if(input.pending('weapon')&&p._canCancel(.55)&&!c.airHeight){input.consume('weapon');if(p.mp>=12){p.mp-=12;this.startRitual(false);return p._hold();}g.hud.notice('霊力が足りない',1);}
  for(let i=0;i<3;i++)if(input.consume('el'+i)){this.mode=i;p.elementIndex=i;g.hud.notice(['幻影剣：射出','幻影剣：周回','幻影剣：雨'][i],1);}
  if(input.pending('magic')){input.consume('magic');if(this.cooldown>0)return undefined;const kind=input.held.guard?'storm':this.mode,cost=kind==='storm'||kind!==0?16:8;if(p.mp>=cost&&this.projectiles.length<18){p.mp-=cost;this.cooldown=.25;this.summon(kind);this.burstPending=kind===0;}else g.hud.notice('霊力が足りない',1);}
  if(this.burstPending&&input.held.magic&&input.holdTime.magic>.4&&p.mp>=16){p.mp-=16;this.summon('burst');this.burstPending=false;}if(!input.held.magic)this.burstPending=false;
  return undefined;
 }
}
