import test from 'node:test';
import assert from 'node:assert/strict';
import { AnimationClip, QuaternionKeyframeTrack, Bone, BoxGeometry, Float32BufferAttribute, Group, Skeleton, SkinnedMesh, Mesh, MeshBasicMaterial, Uint16BufferAttribute, Vector3 } from 'three';
import { KatanaAfterimages } from '../src/game/fx/KatanaAfterimages.js';
function character(){const root=new Group(),model=new Group(),hips=new Bone(),hand=new Bone();hand.position.y=.5;hips.add(hand);const geometry=new BoxGeometry(),n=geometry.attributes.position.count;geometry.setAttribute('skinIndex',new Uint16BufferAttribute(new Uint16Array(n*4),4));const weights=new Float32Array(n*4);for(let i=0;i<n;i++)weights[i*4]=1;geometry.setAttribute('skinWeight',new Float32BufferAttribute(weights,4));const mesh=new SkinnedMesh(geometry,new MeshBasicMaterial());model.add(mesh,hips);mesh.bind(new Skeleton([hips,hand]));root.add(model);root.position.set(2,0,3);return {root,model,hand,mesh};}
test('moving a whole-body afterimage preserves original pose and uses its own skeleton',()=>{const c=character(),fx=new KatanaAfterimages(new Group(),2),before=c.root.position.clone();c.hand.rotation.z=.6;assert.ok(fx.emit(c,new Vector3(),new Vector3(3,0,0)));const image=fx.pool[0];let cloned;image.model.traverse(n=>{if(n.isSkinnedMesh)cloned=n;});assert.notEqual(cloned.skeleton,c.mesh.skeleton);assert.notEqual(cloned.skeleton.bones[1],c.hand);fx.update(.09);assert.ok(image.pivot.position.x>1);assert.ok(c.root.position.equals(before));assert.equal(c.hand.rotation.z,.6);fx.update(.1);assert.equal(image.pivot.visible,false);assert.equal(image.material.opacity,0);fx.dispose();assert.ok(c.mesh.geometry.attributes.position);});
test('the afterimage pool is bounded and resets before later attacks',()=>{const c=character(),fx=new KatanaAfterimages(new Group(),2);assert.ok(fx.emit(c,new Vector3(),new Vector3(1,0,0)));assert.ok(fx.emit(c,new Vector3(),new Vector3(1,0,0)));assert.equal(fx.emit(c,new Vector3(),new Vector3(1,0,0)),false);fx.reset();assert.ok(fx.pool.every(s=>!s.pivot.visible));assert.ok(fx.emit(c,new Vector3(),new Vector3(1,0,0)));});

test('afterimage slash animates cloned joints without animating the source',()=>{const c=character();c.hand.name='hand';c.clips=new Map([['slashHit',new AnimationClip('slashHit',1,[new QuaternionKeyframeTrack('hand.quaternion',[0,1],[0,0,0,1,0,0,Math.sin(.5),Math.cos(.5)])])]]);const fx=new KatanaAfterimages(new Group());fx.emit(c,new Vector3(),new Vector3(1,0,0),.2,'slashHit');fx.update(.1);const hand=fx.pool[0].pairs.get(c.hand);assert.ok(Math.abs(hand.quaternion.z)>.1);assert.equal(c.hand.quaternion.z,0);fx.dispose();});

test('a held scabbard belongs to the ghost without disposing the original asset',()=>{
 const c=character(),fx=new KatanaAfterimages(new Group(),1),scabbard=new Group(),material=new MeshBasicMaterial(),geometry=new BoxGeometry(),mesh=new Mesh(geometry,material);
 scabbard.add(mesh);scabbard.position.set(3,2,1);let disposed=false;material.addEventListener('dispose',()=>disposed=true);
 fx.emit(c,new Vector3(),new Vector3(1,0,0),.2,null,{waist:true,scabbard});
 const ghost=fx.pool[0];assert.notEqual(ghost.scabbard,scabbard);assert.equal(ghost.scabbard.children[0].material,ghost.material);assert.equal(mesh.material,material);assert.deepEqual(scabbard.position.toArray(),[3,2,1]);
 fx.reset();fx.emit(c,new Vector3(),new Vector3(1,0,0));assert.equal(ghost.scabbard,undefined);fx.dispose();assert.equal(disposed,false);assert.ok(geometry.attributes.position);
});
