import test from 'node:test';
import assert from 'node:assert/strict';
import { Bone, Group, PropertyBinding, Quaternion, Vector3 } from 'three';
import { worldRotation } from '../src/game/hero/VergilRig.js';
import { vergilPart, VERGIL_PALETTE } from '../src/game/hero/VergilMaterials.js';
import { readFileSync } from 'node:fs';
test('Vergil world pose preserves imported hierarchy, joint lengths, and scale under a rotated parent',()=>{const root=new Group(),shoulder=new Bone(),elbow=new Bone();root.quaternion.setFromAxisAngle(new Vector3(0,1,0),.8);root.add(shoulder);shoulder.add(elbow);elbow.position.set(.3,0,0);root.updateMatrixWorld(true);const local=elbow.position.clone(),q=new Quaternion().setFromAxisAngle(new Vector3(0,0,1),.4);worldRotation(shoulder,q);assert.ok(shoulder.getWorldQuaternion(new Quaternion()).angleTo(q)<1e-6);assert.equal(elbow.parent,shoulder);assert.ok(elbow.position.equals(local));assert.deepEqual(shoulder.scale.toArray(),[1,1,1]);});
test('video-inspired palette separates coat lining, black clothing and brown boots',()=>{assert.equal(vergilPart('24_undercoat_0'),'lining');assert.equal(vergilPart('24_coat1_0'),'coat');assert.equal(vergilPart('24_boots_0'),'boots');assert.equal(vergilPart('24_head_0'),'skin');assert.notEqual(VERGIL_PALETTE.coat,VERGIL_PALETTE.lining);});
test('original 598-bone GLB remains intact and every bone is preserved in exported motion rest data',()=>{const raw=readFileSync(new URL('../public/models/reference/vergil.glb',import.meta.url)),gltf=JSON.parse(raw.subarray(20,20+raw.readUInt32LE(12)).toString()),clip=JSON.parse(readFileSync(new URL('../public/animations/vergil/stance.json',import.meta.url)));assert.equal(gltf.skins[0].joints.length,598);assert.equal(Object.keys(clip.sourceRest).length,598);for(const index of gltf.skins[0].joints){const name=PropertyBinding.sanitizeNodeName(gltf.nodes[index].name);assert.ok(clip.sourceRest[name]);assert.ok(clip.tracks.some(t=>t.name===name+'.quaternion'));}for(const track of clip.tracks.filter(t=>t.name.endsWith('.quaternion'))){for(let i=0;i<track.values.length;i+=4){assert.ok(Math.abs(Math.hypot(...track.values.slice(i,i+4))-1)<.0001);}}});
