import { MOTION_RIG_PRESETS } from '../game/hero/MotionRigPresets.js';
import { AnimationMixer, Box3, Clock, Color, GridHelper, Group, HemisphereLight, PerspectiveCamera, Scene, Vector3, WebGLRenderer, DirectionalLight, MeshStandardMaterial, SkeletonHelper } from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
import { MOTIONS } from '../game/hero/MotionCatalog.js';
import { restPose, retargetMotion } from '../game/hero/MotionRetarget.js';
const $=id=>document.getElementById(id),canvas=$('bot'),renderer=new WebGLRenderer({canvas,antialias:true}),scene=new Scene();scene.background=new Color('#16212c');const camera=new PerspectiveCamera(45,1,.01,100);camera.position.set(2,1.4,3);const controls=new OrbitControls(camera,canvas);controls.target.set(0,.9,0);scene.add(new HemisphereLight('#e4f3ff','#44404b',2));const light=new DirectionalLight('#ffffff',3);light.position.set(3,5,2);scene.add(light,new GridHelper(6,24));
let model,mixer,action,data,current,helper,playing=true,request=0;
$('model').addEventListener('change',()=>{const id=$('model').value.split('/').pop().split('.')[0];$('mapping').value=JSON.stringify({boneMap:MOTION_RIG_PRESETS[id]??{},rotationOffsets:{}},null,2);});
for(const [id,m]of Object.entries(MOTIONS)){const o=document.createElement('option');o.value=id;o.textContent=m.name;$('motion').append(o);}
async function selectMotion(){try{const r=await fetch('./animations/katana/'+$('motion').value+'.json');if(!r.ok)throw Error('保存データを準備中のモーションです');data=await r.json();apply();}catch(e){$('status').textContent=e.message;}}
async function load(url){const seq=++request;$('status').textContent='キャラクターを読み込み中…';try{const next=url.endsWith('.fbx')?await new FBXLoader().loadAsync(url):(await new GLTFLoader().loadAsync(url)).scene;if(seq!==request)return;model?.removeFromParent();model=next;restPose(model);model.traverse(n=>{if(n.isMesh){const mats=Array.isArray(n.material)?n.material:[n.material];n.material=mats.map(m=>new MeshStandardMaterial({color:m.color?.getHex()??0xabc0cf,map:m.map??null,roughness:.65,metalness:.05,side:m.side,transparent:m.transparent,opacity:m.opacity}));for(const m of n.material)if(m.color.r+m.color.g+m.color.b<.08)m.color.set('#9bb3c4');if(!Array.isArray(mats)||mats.length===1)n.material=n.material[0];}});const box=new Box3().setFromObject(model),size=box.getSize(new Vector3()),scale=1.8/Math.max(.01,size.y);const wrapper=new Group();wrapper.scale.setScalar(scale);wrapper.add(model);if(window.motionBot?.wrapper)window.motionBot.wrapper.removeFromParent();scene.add(wrapper);helper?.removeFromParent();helper=new SkeletonHelper(model);helper.material.depthTest=false;helper.visible=$('bones').checked;scene.add(helper);model.position.y-=box.min.y;mixer=new AnimationMixer(model);window.motionBot={model,mixer,wrapper,apply,sourceUrl:url};await selectMotion();}catch(e){$('status').textContent='読み込み失敗：'+e.message;}}
function apply(){if(!data||!model)return;try{mixer.stopAllAction();const options=JSON.parse($('mapping').value);current=retargetMotion(data,model,{...options,height:+$('height').value,chest:+$('chest').value});action=mixer.clipAction(current.clip);action.play();$('time').value=0;$('status').textContent=`${data.name}：${current.mapped.length}トラック対応。未対応${current.missing.length}ボーン。`+(current.missing.length?' 対応表を調整：'+current.missing.slice(0,8).join('、'):'');window.motionBot.current=current;}catch(e){$('status').textContent='補正を確認してください：'+e.message;}}
$('bones').onchange=()=>{if(helper)helper.visible=$('bones').checked;};
$('motion').onchange=selectMotion;$('model').onchange=()=>load($('model').value);$('apply').onclick=apply;$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'一時停止':'再生';};$('time').oninput=()=>{if(action){playing=false;$('play').textContent='再生';action.time=+$('time').value*current.clip.duration;mixer.update(0);}};
$('local-model').onchange=async()=>{const f=$('local-model').files[0];if(!f)return;const url=URL.createObjectURL(f);try{await load(url);}finally{URL.revokeObjectURL(url);}};
$('local-motion').onchange=async()=>{try{data=JSON.parse(await $('local-motion').files[0].text());apply();}catch(e){$('status').textContent='モーションJSONを読み込めません：'+e.message;}};
$('save').onclick=()=>{if(!current)return;const json=current.clip.toJSON();json.sourceRest=restPose(model);json.reconstruction=true;json.correction={...JSON.parse($('mapping').value),height:+$('height').value,chest:+$('chest').value,speed:+$('speed').value};const url=URL.createObjectURL(new Blob([JSON.stringify(json)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=$('motion').value+'-adjusted.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('save-library').onclick=async()=>{try{$('status').textContent='元骨格と全モーションをまとめています…';const clips=await Promise.all(Object.keys(MOTIONS).map(async id=>{const r=await fetch('./animations/katana/'+id+'.json');if(!r.ok)throw Error(id+'の保存データがありません');return {id,...await r.json()};}));const library={schema:'samurai-motion-library/v1',sourceSkeleton:clips[0].sourceRest,sourceUnits:'centimetres; source character normalised to 1.8m in game',rigPresets:MOTION_RIG_PRESETS,motions:clips};const url=URL.createObjectURL(new Blob([JSON.stringify(library)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='black-rain-motion-library.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='骨格と21モーションを保存しました';}catch(e){$('status').textContent=e.message;}};
const clock=new Clock();function render(){requestAnimationFrame(render);const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();const dt=Math.min(.05,clock.getDelta());if(mixer&&playing){mixer.update(dt*+$('speed').value);if(action)$('time').value=action.time/current.clip.duration;}controls.update();renderer.render(scene,camera);}load($('model').value);render();
