import { AdditiveBlending, Color, DoubleSide, NormalBlending, ShaderMaterial, Vector3 } from 'three';
export function cutMaterial(color){return new ShaderMaterial({transparent:true,depthWrite:false,side:DoubleSide,blending:AdditiveBlending,toneMapped:false,uniforms:{uColor:{value:new Color(color)},uOpacity:{value:0},uAge:{value:0},uCutStart:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 uColor;uniform float uOpacity;uniform float uAge;uniform float uCutStart;varying vec2 vUv;void main(){float edge=1.-abs(vUv.y*2.-1.);float core=smoothstep(.45,.92,edge);float feather=smoothstep(.01,.35,edge);gl_FragColor=vec4(mix(uColor*1.5,vec3(2.2),core),uOpacity*feather);}'});}
export function cloudMaterial(steps=12){return new ShaderMaterial({transparent:true,depthWrite:false,blending:NormalBlending,toneMapped:false,uniforms:{uPhase:{value:0},uOpacity:{value:0},uCamera:{value:new Vector3()},uSteps:{value:steps}},vertexShader:'varying vec3 vPoint;void main(){vPoint=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`
 uniform float uPhase;uniform float uOpacity;uniform vec3 uCamera;uniform int uSteps;varying vec3 vPoint;
 float hash(vec3 p){p=fract(p*.3183099+vec3(.11,.17,.23));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
 float noise(vec3 p){vec3 a=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(a),hash(a+vec3(1,0,0)),f.x),mix(hash(a+vec3(0,1,0)),hash(a+vec3(1,1,0)),f.x),f.y),mix(mix(hash(a+vec3(0,0,1)),hash(a+vec3(1,0,1)),f.x),mix(hash(a+vec3(0,1,1)),hash(a+vec3(1,1,1)),f.x),f.y),f.z);}
 float cloud(vec3 p){float a=noise(p);a+=.5*noise(p*2.03+1.7);a+=.25*noise(p*4.11-2.1);return a/1.75;}
 void main(){vec3 ray=normalize(vPoint-uCamera);float b=dot(uCamera,ray),c=dot(uCamera,uCamera)-.95*.95;float h=b*b-c;if(h<0.)discard;float lo=max(0.,-b-sqrt(h)),hi=-b+sqrt(h);float stepSize=(hi-lo)/float(uSteps);vec3 colour=vec3(0);float alpha=0.;
 for(int i=0;i<16;i++){if(i>=uSteps)break;vec3 point=uCamera+ray*(lo+(float(i)+.5)*stepSize);vec3 flow=point*3.8+vec3(uPhase*1.1,-uPhase*2.7,uPhase*.6);float density=smoothstep(.32,.7,cloud(flow))*(1.-smoothstep(.55,.95,length(point)));float electric=pow(noise(flow*3.2+uPhase*5.),22.);vec3 tint=mix(vec3(.008,.003,.024),vec3(.18,.025,.65),density)+electric*vec3(.45,.65,1.)*1.5;float a=density*stepSize*uOpacity*3.2;colour+=(1.-alpha)*a*tint;alpha+=(1.-alpha)*a;}
 if(alpha<.002)discard;gl_FragColor=vec4(colour/max(alpha,.001),min(alpha,.65));}
 `});}
