"""Play the katana techniques through real inputs; save captures and reusable clips."""
import json,os
from pathlib import Path
from playwright.sync_api import sync_playwright
out=Path('/tmp/vergil-techniques');out.mkdir(exist_ok=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',args=['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
 p=b.new_page(viewport={'width':960,'height':640});errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
 p.goto(os.environ.get('GAME_URL','http://127.0.0.1:4181/')+'?q=low&dyn=0');p.wait_for_function('window.app?.game?.state==="title"',timeout=240000);p.evaluate('app.stop()');p.get_by_role('button',name='はじめる',exact=True).click()
 p.evaluate('''()=>{const g=app.game;g.flow.update=()=>{};g.director.clear();g.magic.clear();g.flow._place(g.playerPosition.clone().set(0,0,124),0);g.hud.setVisible(false);g.touch.setVisible(false);app.simulate(.5);window.clean=()=>{g.input.reset();g.player.revive();g.player.invulnerable=999;g.player.special=1;g.player.mp=100;g.flow._place(g.playerPosition.clone().set(0,0,124),0);app.simulate(.3);};window.camera=()=>{const at=g.player.character.position,c=app.rig.camera;c.position.set(at.x+2,at.y+1.6,at.z+3);c.lookAt(at.x,at.y+1,at.z);c.fov=42;c.updateProjectionMatrix();app.scene.updateMatrixWorld(true);app.post.render();};}''')
 assert p.evaluate('app.game.player.techniques.assets.status.force && app.game.player.techniques.assets.status.end')
 results={}
 # A real distant target, with AI frozen, proves remote damage and projectile contact.
 p.evaluate('''()=>{const g=app.game,a=g.director.spawn('infinian',0,130,Math.PI);a.hp=a.maxHp=10000;a.cooldown=999;a.maxPosture=10000;a.update=()=>{};g.player.lockTarget=a.enemy;window.target=a;app.simulate(.2);}''')
 for key,label in [('e','judgement'),('f','end')]:
  p.evaluate('clean()');before=p.evaluate('target.hp');p.keyboard.press(key);p.evaluate('app.simulate(.48);camera()');p.screenshot(path=str(out/(label+'.png')))
  if label=='end':
   p.evaluate('app.simulate(1.26)');assert p.evaluate('app.game.player.techniques.assets.endPool.some(s=>s.mesh.visible)');p.evaluate('(()=>{const c=app.rig.camera,at=app.game.playerPosition;c.position.set(at.x+5,at.y+2.2,at.z+3);c.lookAt(at.x,at.y+1,at.z+3);c.fov=55;c.updateProjectionMatrix();app.scene.updateMatrixWorld(true);app.post.render();})()');p.screenshot(path=str(out/'end-material.png'))
  p.evaluate('app.simulate('+('2.6' if label=='end' else '1.8')+')');after=p.evaluate('target.hp')
  assert after<before,(label,before,after)
  assert p.evaluate('app.game.player.techniques.ritual===null'),label
  results[label]={'damage':before-after,'state':p.evaluate('app.game.player.state')}
 p.evaluate('clean()');p.keyboard.press('r');p.evaluate('app.simulate(.1);camera()');assert p.evaluate('app.game.player.arts.transform')>7;p.screenshot(path=str(out/'dragon-human.png'));assert p.evaluate('!app.game.form.active');p.keyboard.press('r');p.evaluate('app.simulate(.1)');assert p.evaluate('app.game.player.arts.transform')==0
 for key,mode in [('1',0),('2',1),('3',2)]:
  p.evaluate('clean()');p.keyboard.press(key);p.evaluate('app.simulate(.03)');assert p.evaluate('app.game.player.techniques.mode')==mode
  before=p.evaluate('target.hp');p.keyboard.press('q');p.evaluate('app.simulate(.1);camera()');p.screenshot(path=str(out/f'phantom-{mode}.png'));p.evaluate('app.simulate(1.8)');after=p.evaluate('target.hp');assert after<before,(mode,before,after);assert p.evaluate('app.game.player.techniques.projectiles.length')==0;results['phantom-'+str(mode)]={'damage':before-after}
 p.evaluate('clean()');p.keyboard.down('q');p.evaluate('app.simulate(.6)');assert p.evaluate('app.game.player.techniques.projectiles.length')>1;p.keyboard.up('q');p.evaluate('app.simulate(2)')
 p.evaluate('clean()');p.keyboard.down('k');p.keyboard.press('q');p.evaluate('app.simulate(.1)');assert p.evaluate('app.game.player.techniques.projectiles.length')==4;p.keyboard.up('k');p.evaluate('app.simulate(2)')
 p.evaluate('clean()');p.keyboard.press('e');p.evaluate('app.simulate(.1)');p.keyboard.press('k');p.evaluate('app.simulate(.05)');assert p.evaluate('app.game.player.techniques.ritual===null')
 for key in ['v','j']:
  p.evaluate('clean()');p.keyboard.press(key);p.evaluate('app.simulate(.3);camera()');p.screenshot(path=str(out/('launcher.png' if key=='v' else 'combo.png')));p.evaluate('app.simulate(1)');assert p.evaluate('app.game.player.state')=='free'
 p.evaluate('clean()');p.keyboard.press('Space');p.evaluate('app.simulate(.06)');p.keyboard.down('j');p.evaluate('app.simulate(.35);camera()');p.screenshot(path=str(out/'air-dive.png'));p.keyboard.up('j');p.evaluate('app.simulate(2)');assert p.evaluate('app.game.player.state')=='free'
 # Original 3D effects follow the draw -> remote cut -> fade sequence.
 p.evaluate('clean()');p.keyboard.press('e');p.evaluate('app.simulate(.31)')
 assert p.evaluate('app.game.player.techniques.assets.slashPool.some(s=>s.mesh.visible)')
 assert p.evaluate('app.game.player.techniques.assets.riftPool.every(s=>!s.mesh.visible)')
 p.evaluate('app.simulate(.1)');assert p.evaluate('app.game.player.techniques.assets.riftPool.some(s=>s.mesh.visible)')
 p.evaluate('app.simulate(.8)');assert p.evaluate('[...app.game.player.techniques.assets.slashPool,...app.game.player.techniques.assets.riftPool].every(s=>!s.mesh.visible)')
 p.evaluate('clean()');p.keyboard.press('f');p.evaluate('app.simulate(.73)');assert p.evaluate('app.game.player.techniques.assets.burstPool.every(s=>!s.mesh.visible)');p.evaluate('app.simulate(3.2)');assert p.evaluate('app.game.player.arts.mode')=='sheathed';assert p.evaluate('app.game.player.techniques.assets.burstPool.some(s=>s.mesh.visible)')
 p.evaluate('app.simulate(.35)');assert p.evaluate('app.game.player.techniques.assets.burstPool.every(s=>!s.mesh.visible)')
 p.evaluate('clean()');p.keyboard.press('f');p.evaluate('app.simulate(2.8)');before=p.evaluate('target.hp');p.keyboard.press('k');p.evaluate('app.simulate(1.6)');assert p.evaluate('app.game.player.techniques.endBurst===null');assert p.evaluate('app.game.player.techniques.assets.burstPool.every(s=>!s.mesh.visible)');assert p.evaluate('target.hp')==before
 results['original-effects']={'drawBeforeRemoteCut':True,'finalBurstVisible':True,'allExpired':True}
 # Additional cuts use real E presses, resource costs and interruptible timing.
 p.evaluate('clean();app.game.player.mp=100');before=p.evaluate('target.hp');p.keyboard.press('e');p.evaluate('app.simulate(.46)');p.keyboard.press('e');p.evaluate('app.simulate(.50)');p.keyboard.press('e');p.evaluate('app.simulate(1.2)');chain=p.evaluate('({damage:0,mp:app.game.player.mp,state:app.game.player.state,ritual:app.game.player.techniques.ritual})');chain['damage']=before-p.evaluate('target.hp');assert chain['damage']==72,chain;assert chain['ritual'] is None and chain['state']=='free',chain;results['judgement-chain']=chain
 p.evaluate('clean();app.game.player.mp=100');before=p.evaluate('target.hp');p.keyboard.press('Space');p.evaluate('app.simulate(.08)');p.keyboard.press('e');p.evaluate('app.simulate(.06)');assert p.evaluate('app.game.player.techniques.ritual?.airborne')==True;p.evaluate('app.simulate(1.7)');air=p.evaluate('({height:app.game.player.character.airHeight,state:app.game.player.state,ritual:app.game.player.techniques.ritual})');air['damage']=before-p.evaluate('target.hp');assert air['damage']==24 and air['state']=='free' and air['ritual'] is None,air;assert abs(air['height'])<.001,air;results['judgement-air']=air
 p.evaluate('clean();app.game.player.mp=0');p.keyboard.press('e');p.evaluate('app.simulate(.1)');assert p.evaluate('app.game.player.techniques.ritual===null')
 p.evaluate('clean();app.game.player.mp=100');p.keyboard.press('e');p.evaluate('app.simulate(.45)');p.keyboard.press('e');p.evaluate('app.simulate(.02)');p.keyboard.press('k');p.evaluate('app.simulate(.8)');assert p.evaluate('app.game.player.techniques.ritual===null')
 p.evaluate('clean()');p.keyboard.press('Space');p.evaluate('app.simulate(.12)');p.keyboard.press('v');p.evaluate('app.simulate(.05)');assert p.evaluate('app.game.player.move?.config.id')=='aerial-b';p.evaluate('app.simulate(2)');assert p.evaluate('app.game.player.state')=='free';results['aerial-b']={'input':'Space then V','returnedToFree':True}
 p.evaluate('clean()');p.keyboard.press('t');p.evaluate('app.simulate(.5)');assert p.evaluate('app.game.player.techniques.taunt!==null');p.keyboard.press('k');p.evaluate('app.simulate(.1)');assert p.evaluate('app.game.player.techniques.taunt===null');p.keyboard.up('k');p.evaluate('clean()');p.keyboard.press('t');p.evaluate('app.simulate(3)');assert p.evaluate('app.game.player.techniques.taunt===null&&app.game.player.arts.mode==="sheathed"');results['taunt']={'cancelled':True,'returnedToSheathed':True}
 # Finisher moves the actual root, returns, and relinquishes body lift on interruption.
 p.evaluate('clean()');home=p.evaluate('app.game.player.character.position.toArray()');p.keyboard.press('f');p.evaluate('app.simulate(.8)');during=p.evaluate('app.game.player.character.position.toArray()');assert sum((a-b)**2 for a,b in zip(home,during))>.1;p.keyboard.press('k');p.evaluate('app.simulate(.05)');assert p.evaluate('app.game.player.techniques.ritual===null&&!app.game.player.techniques.traversal.active');assert abs(p.evaluate('app.game.player.character.tilt.position.y'))<.1;p.keyboard.up('k');p.evaluate('clean()');p.keyboard.press('f');p.evaluate('app.simulate(4.5)');assert p.evaluate('app.game.player.character.position.distanceTo(new app.game.player.character.position.constructor(0,0,124))')<.01;results['end-body']={'movedRoot':True,'returnedHome':True,'interruptReleasesLift':True}
 # Export real runtime local bone tracks, including IK corrections, at 30 fps.
 export=p.evaluate('''()=>{const g=app.game,p=g.player,c=p.character,clips=[];g.player.lockTarget=null;g.director.clear();const names={quickDraw:'黒雨・抜刀一閃',k1:'黒雨・抜き付け',k2:'黒雨・斬り返し',k3:'黒雨・立ち上がり斬り',k4:'黒雨・二連斬',k5:'黒雨・袈裟締め',branchB:'黒雨・間合い二連',branchC:'黒雨・三連返し',heavy:'黒雨・天翔居合',launcher:'黒雨・昇竜斬',rising:'黒雨・疾走昇斬','jump-katana':'黒雨・空中二連','dive-katana':'黒雨・落下斬','aerial-b':'黒雨・空中連斬弐',counter:'黒雨・弾き返し',execute:'黒雨・止め斬り'};
 for(const m of [p.quickDraw,...p.combo,p.heavy,p.counter,p.execute,p.launcher,p.risingMove,p.jumpMove,p.diveMove,p.aerialBMove,p.branchB,p.branchC]){clean();const id=m.config.id,duration=m.action.getClip().duration*(m.config.clipTo-m.config.clipFrom)/m.config.timeScale,frames=Math.ceil(duration*30),bones=[...new Set(c.bones.values())],tracks=bones.map(b=>({name:b.name+'.quaternion',type:'quaternion',times:[],values:[]}));const hips=c.getBone('Hips'),hip={name:hips.name+'.position',type:'vector',times:[],values:[]};if(m.config.airborne)c.hop.start();p._startMove(m,null);for(let i=0;i<=frames;i++){if(i)app.simulate(1/30);for(let j=0;j<bones.length;j++){tracks[j].times.push(i/30);tracks[j].values.push(...bones[j].quaternion.toArray().map(v=>+v.toFixed(6)));}hip.times.push(i/30);hip.values.push(...hips.position.toArray().map(v=>+v.toFixed(6)));}clips.push({id,name:names[id],duration:frames/30,fps:30,tracks:[...tracks,hip],reconstruction:!m.config.referenceMotion,importedSource:m.config.referenceMotion??null,rootMotion:'Movement and airborne travel remain controlled by gameplay; local bone clip only.'});}
 clean();p.arts.charge();app.simulate(.4);const bones=[...new Set(c.bones.values())];clips.push({id:'stance',name:'黒雨・次元斬の構え',duration:1,fps:30,reconstruction:true,tracks:bones.map(b=>({name:b.name+'.quaternion',type:'quaternion',times:[0,1],values:[...b.quaternion.toArray(),...b.quaternion.toArray()]}))});const sample=(id,name,seconds,begin,step=()=>{})=>{clean();begin();const bones=[...new Set(c.bones.values())],tracks=bones.map(b=>({name:b.name+'.quaternion',type:'quaternion',times:[],values:[]})),hip=c.getBone('Hips'),ht={name:hip.name+'.position',type:'vector',times:[],values:[]},count=Math.ceil(seconds*30),origin=c.position.clone(),heading=c.facing,movement={units:"metres",frame:"source forward +Z",source:"runtime capture; collision-constrained",samples:[]};for(let i=0;i<=count;i++){if(i){step(i/30);app.simulate(1/30);}for(let j=0;j<bones.length;j++){tracks[j].times.push(i/30);tracks[j].values.push(...bones[j].quaternion.toArray().map(v=>+v.toFixed(6)));}if(id==='end'){const d=c.position.clone().sub(origin),x=d.x*Math.cos(heading)-d.z*Math.sin(heading),z=d.x*Math.sin(heading)+d.z*Math.cos(heading);movement.samples.push({t:i/30,position:[x,p.techniques.traversal.lift,z],yaw:Math.atan2(Math.sin(c.facing-heading),Math.cos(c.facing-heading))});}ht.times.push(i/30);ht.values.push(...hip.position.toArray().map(v=>+v.toFixed(6)));}clips.push({id,name,duration:count/30,fps:30,tracks:[...tracks,ht],reconstruction:true,rootMotion:id==='end'?'Metre-based travel is stored separately from bone tracks.':'Gameplay movement is not included.',...(id==='end'?{movement}: {})});};
 sample('flourish','黒雨・血払い納刀',2.8,()=>p.arts.startSheath(true));sample('taunt','黒雨・掲刀挑発',2.8,()=>p.techniques.startTaunt());sample('judgement','黒雨・次元斬',.75,()=>p.techniques.startRitual(false));sample('judgement-air','黒雨・空中次元斬',1.4,()=>{c.hop.start();app.simulate(.06);p.techniques.startRitual(false);});sample('judgement-chain','黒雨・連続次元斬',1.9,()=>{p.mp=100;p.techniques.startRitual(false);},()=>{const r=p.techniques.ritual;if(r&&!r.end&&!r.queued&&r.chain<3&&r.t>=.45){g.input.press('weapon');g.input.release('weapon');}});sample('end','黒雨・次元斬絶',4.5,()=>p.techniques.startRitual(true));sample('sheath','黒雨・納刀所作',2.8,()=>p.arts.startSheath());sample('sheathed','黒雨・納刀直立',4.2,()=>{p.arts.startSheath();app.simulate(3);});sample('walk','黒雨・鞘携行歩き',1.3,()=>{p.arts.startSheath();app.simulate(3);g.input.keys.add('KeyW');},()=>{});g.input.keys.delete('KeyW');sample('dodge','黒雨・残影回避',.7,()=>p._startDodge());for(const [id,kind,name] of [['phantom-shot',0,'黒雨・幻影剣射出'],['phantom-orbit',1,'黒雨・周回剣'],['phantom-rain',2,'黒雨・降雨剣'],['phantom-burst','burst','黒雨・連続射出'],['phantom-storm','storm','黒雨・包囲剣']])sample(id,name,1.8,()=>p.techniques.summon(kind));
 const bind={};c.model.traverse(o=>{if(o.isSkinnedMesh){const sk=o.skeleton;for(let i=0;i<sk.bones.length;i++){const b=sk.bones[i],parent=sk.bones.indexOf(b.parent),matrix=sk.boneInverses[i].clone().invert();if(parent>=0)matrix.premultiply(sk.boneInverses[parent]);const at=c.position.clone(),q=c.root.quaternion.clone(),scale=c.root.scale.clone();matrix.decompose(at,q,scale);bind[b.name]={position:at.toArray(),quaternion:q.toArray(),scale:scale.toArray(),parent:b.parent?.isBone?b.parent.name:null};}}});c.model.traverse(b=>{if(b.isBone&&!bind[b.name])bind[b.name]={position:b.position.toArray(),quaternion:b.quaternion.toArray(),scale:b.scale.toArray(),parent:b.parent?.isBone?b.parent.name:null};});for(const clip of clips)clip.sourceRest=bind;return clips;}''')
 root=Path('public/animations/katana');root.mkdir(parents=True,exist_ok=True)
 for clip in export:
  ident=clip.pop('id');(root/(ident+'.json')).write_text(json.dumps(clip,ensure_ascii=False,separators=(',',':'))+'\n')
 assert not errors,errors
 results['clips']=len(export);results['errors']=errors;(out/'results.json').write_text(json.dumps(results,indent=2));print(json.dumps(results));b.close()
