import json,os,subprocess
from pathlib import Path
from playwright.sync_api import sync_playwright
out=Path(os.environ.get('CAPTURE_DIR','/tmp/vergil-comparison-after'));out.mkdir(exist_ok=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',args=['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
 p=b.new_page(viewport={'width':640,'height':426});p.goto('http://127.0.0.1:4181/?q=low&dyn=0');p.wait_for_function('window.app?.game?.state==="title"',timeout=240000);p.evaluate('app.stop()');p.get_by_role('button',name='はじめる',exact=True).click()
 if os.environ.get('CAPTURE_SIMPLE_STAGE')=='1':p.evaluate("()=>{const g=app.game,lights=[];g.stage.group.traverse(o=>{if(o.isLight&&lights.length<2)lights.push(o.clone());});g.stage.group.visible=false;for(const l of lights){l.position.set(2,3,126);l.intensity=4;l.castShadow=false;app.scene.add(l);}app.renderer.gl.shadowMap.autoUpdate=false;}")
 p.evaluate('''async()=>{const g=app.game;g.flow.update=()=>{};g.director.clear();g.magic.clear();g.flow._place(g.playerPosition.clone().set(0,0,124),0);await g.weapons.swords.select('mythical');g.hud.setVisible(false);g.touch.setVisible(false);g.player.invulnerable=999;window.poseCamera=()=>{const at=g.player.character.position,c=app.rig.camera;c.position.set(at.x+2.8,at.y+1.7,at.z+4);c.lookAt(at.x,at.y+1,at.z);if(['judgement','end','phantom-shot','phantom-orbit','phantom-rain'].includes(window.caseKind)){c.position.set(at.x+6,at.y+3,at.z+8);c.lookAt(at.x,at.y+1,at.z+3);}c.fov=38;c.updateProjectionMatrix();app.scene.updateMatrixWorld(true);app.post.render();};}''')
 cases=p.evaluate("Object.keys(Object.fromEntries(app.game.player.moves.filter(m=>m.action).map(m=>[m.config.id,m])))")
 cases=[c for c in cases if c not in ['cast','kick','jump']] + ['judgement','end','phantom-shot','phantom-orbit','phantom-rain','stance','sheath','walk','dodge']
 wanted=os.environ.get('CAPTURE_ONLY');cases=[c for c in cases if not wanted or c in wanted.split(',')]
 for kind in cases:
  folder=out/kind;folder.mkdir(exist_ok=True);rows=[];fps=15 if kind in ['quickDraw','heavy'] else 10
  p.evaluate("""kind=>{const g=app.game,p=g.player;g.input.reset();g.director.clear();p.techniques.reset();p.arts.cancel();p.revive();p.setWeapon('katana');g.flow._place(g.playerPosition.clone().set(0,0,124),0);app.simulate(.2);if(['quickDraw','heavy','stance','walk'].includes(kind)){p.arts.startSheath();app.simulate(2);}window.caseKind=kind;if(['judgement','end','phantom-shot','phantom-orbit','phantom-rain'].includes(kind)){const a=g.director.spawn('infinian',0,127,Math.PI);a.hp=a.maxHp=10000;a.maxPosture=10000;a.cooldown=999;a.update=()=>{};p.lockTarget=a.enemy;}if(kind==='quickDraw'||kind==='heavy'||kind==='stance')g.input.press('attack');else if(kind==='judgement'||kind==='end')p.techniques.startRitual(kind==='end');else if(kind.startsWith('phantom'))p.techniques.summon({'phantom-shot':0,'phantom-orbit':1,'phantom-rain':2}[kind]);else if(kind==='sheath')p.arts.startSheath();else if(kind==='walk')g.input.keys.add('KeyW');else if(kind==='dodge')p._startDodge();else{const m=p.moves.find(m=>m.config.id===kind);if(m?.config.airborne)p.character.hop.start();if(m)p._startMove(m,null);}}""",kind)
  for i in range(round(2.8*fps)):
   row=p.evaluate("""({i,kind,fps})=>{const g=app.game;if(i===(kind==='quickDraw'?1:Math.round(.65*fps))&&kind!=='stance')g.input.release('attack');app.simulate((1/fps)*(1-1e-10),1/60);poseCamera();const p=g.player,c=p.character;return {t:(i+1)/fps,mode:p.arts.mode,move:p.move?.config.id,phase:p.move?.phase,rig:Object.fromEntries([...new Set(c.bones.values())].map(b=>[b.name,{quaternion:b.quaternion.toArray(),position:b.getWorldPosition(c.position.clone()).toArray()}])),bones:Object.fromEntries(['Hips','Spine2','Head','RightArm','RightForeArm','RightHand','LeftArm','LeftForeArm','LeftHand','LeftFoot','RightFoot'].map(n=>[n,c.getBone(n).getWorldPosition(c.position.clone()).toArray()]))};}""",{'i':i,'kind':kind,'fps':fps});rows.append(row);p.screenshot(path=str(folder/f'{i:03}.png'))
  (out/(kind+'-timeline.json')).write_text(json.dumps(rows,indent=2))
  subprocess.run(['ffmpeg','-y','-framerate',str(fps),'-i',str(folder/'%03d.png'),'-vf',"drawtext=text='"+kind+" - local revised capture':x=12:y=12:fontsize=16:fontcolor=white:box=1:boxcolor=black@0.7",'-c:v','libx264','-pix_fmt','yuv420p',str(out/(kind+'.mp4')),'-loglevel','error'],check=True)
  print(json.dumps({'recorded':kind,'fps':fps,'frames':len(rows)}),flush=True)
 b.close()
